<Project>
  <PropertyGroup>
    <Copyright>Copyright © 2013-2025 Akka.NET Team</Copyright>
    <Authors>Akka.NET Team</Authors>
    <VersionPrefix>1.5.37.1</VersionPrefix>
    <PackageReleaseNotes>* [Akka.Hosting.TestKit: Fixed issue with `xUnitLogger` throwing `NotImplementedException` when used with scoped logging](https://github.com/akkadotnet/Akka.Hosting/pull/570).</PackageReleaseNotes>
    <PackageIcon>akkalogo.png</PackageIcon>
    <PackageProjectUrl>
      https://github.com/akkadotnet/Akka.Hosting
    </PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <LibraryFramework>netstandard2.0</LibraryFramework>
    <NetLibraryFramework>net6.0</NetLibraryFramework>
    <TestsNetCoreFramework>net8.0</TestsNetCoreFramework>
    <XunitVersion>2.8.1</XunitVersion>
    <TestSdkVersion>17.11.1</TestSdkVersion>
    <CoverletVersion>6.0.3</CoverletVersion>
    <XunitRunneVisualstudio>3.1.3</XunitRunneVisualstudio>
    <AkkaVersion>1.5.46</AkkaVersion>
    <MicrosoftExtensionsVersion>[6.0.0,)</MicrosoftExtensionsVersion>
    <SystemTextJsonVersion>[6.0.10,)</SystemTextJsonVersion>
  </PropertyGroup>
  <!-- SourceLink support for all Akka.NET projects -->
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)\docs\images\akkalogo.png" Pack="true" Visible="false" PackagePath="\" />
    <None Include="$(MSBuildThisFileDirectory)\README.md" Pack="true" Visible="false" PackagePath="\" />
  </ItemGroup>
  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>