name: pr_validation

on:
  push:
    branches:
      - master
      - dev
      - main
      - feature/*
  pull_request:
    branches:
      - master
      - dev
      - main
      - feature/*

jobs:
  test:
    name: Test-${{matrix.os}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          lfs: true
          fetch-depth: 0

      - name: "Install .NET SDK"
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: "./global.json"

      - name: "Update release notes"
        shell: pwsh
        run: |
          ./build.ps1

      - name: "dotnet build"
        run: dotnet build -c Release

      # .NET Framework tests can't run reliably on Linux, so we only do .NET 8

      - name: "dotnet test"
        shell: bash
        run: dotnet test -c Release

      - name: "dotnet pack"
        run: dotnet pack -c Release -o ./bin/nuget
